In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Configuraraciones
pd.set_option('display.max_columns', None)

In [3]:
# Se carga el Dataset
test = pd.read_csv('../data/test.csv')

In [4]:
# Se carga el Dataset
train = pd.read_csv('../data/train.csv')

In [5]:
test.shape

(25976, 25)

In [6]:
train.shape

(103904, 25)

In [7]:
test.sample(10)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
24484,24484,41617,Male,Loyal Customer,21,Business travel,Eco Plus,1269,5,4,4,4,5,5,4,5,3,1,4,4,5,5,44,37.0,satisfied
4341,4341,95262,Female,Loyal Customer,55,Personal Travel,Eco,239,1,4,1,3,2,4,4,3,3,1,3,2,3,1,31,11.0,neutral or dissatisfied
22029,22029,113768,Male,Loyal Customer,60,Personal Travel,Eco,226,3,5,3,4,2,3,3,2,5,5,4,3,4,2,0,0.0,neutral or dissatisfied
13660,13660,27867,Male,Loyal Customer,24,Business travel,Eco Plus,1448,4,5,5,5,4,4,5,4,3,2,3,1,3,4,1,0.0,satisfied
14128,14128,68271,Female,Loyal Customer,37,Personal Travel,Eco,631,2,4,2,5,2,2,2,2,5,4,4,4,4,2,0,0.0,neutral or dissatisfied
10557,10557,73375,Female,disloyal Customer,26,Business travel,Eco,1144,3,3,3,3,1,3,1,1,2,1,3,2,3,1,7,16.0,neutral or dissatisfied
25063,25063,38258,Male,disloyal Customer,55,Business travel,Eco,1050,3,3,3,4,2,3,2,2,2,5,4,2,3,2,6,54.0,neutral or dissatisfied
2873,2873,120547,Female,Loyal Customer,52,Business travel,Business,2176,4,4,4,4,4,5,5,5,5,5,5,4,5,5,54,35.0,satisfied
17778,17778,66776,Female,disloyal Customer,17,Business travel,Eco,802,2,2,2,2,1,2,1,1,5,5,5,4,5,1,0,0.0,neutral or dissatisfied
13805,13805,91975,Male,Loyal Customer,32,Business travel,Business,2586,3,3,3,3,5,5,5,5,4,4,3,3,5,5,19,19.0,satisfied

In [8]:
train.sample(10)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
17139,17139,99727,Female,Loyal Customer,53,Business travel,Business,361,4,4,5,4,2,4,5,4,4,4,4,3,4,4,23,15.0,satisfied
67277,67277,54575,Female,Loyal Customer,10,Personal Travel,Eco Plus,802,3,1,3,3,2,3,2,2,2,3,2,1,3,2,0,0.0,neutral or dissatisfied
44606,44606,88454,Female,Loyal Customer,48,Business travel,Business,3358,4,4,4,4,5,2,4,5,5,5,5,3,5,3,112,130.0,satisfied
38720,38720,12539,Female,disloyal Customer,38,Business travel,Eco,871,1,1,1,4,3,1,3,3,2,3,4,4,4,3,0,12.0,neutral or dissatisfied
25527,25527,93117,Male,Loyal Customer,50,Business travel,Business,3681,5,3,2,2,3,3,3,5,5,4,5,4,5,3,8,0.0,neutral or dissatisfied
84085,84085,18396,Female,Loyal Customer,38,Personal Travel,Eco,378,5,4,5,3,2,5,2,2,1,1,4,3,3,2,6,0.0,satisfied
51557,51557,116991,Female,Loyal Customer,49,Business travel,Business,2843,1,1,1,1,4,4,5,4,4,4,4,5,4,4,58,35.0,satisfied
64094,64094,85360,Female,Loyal Customer,21,Personal Travel,Eco Plus,813,3,4,3,3,3,3,3,3,4,5,4,5,4,3,1,0.0,neutral or dissatisfied
26650,26650,72216,Female,Loyal Customer,44,Business travel,Business,921,2,2,2,2,3,5,5,3,3,4,3,5,3,5,1,0.0,satisfied
78801,78801,68310,Female,Loyal Customer,40,Business travel,Business,2165,3,3,3,3,4,3,5,4,4,4,4,4,4,3,0,0.0,satisfied